# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

name:                tzbot
version:             0.1.0.0
github:              serokell/tzbot
license:             MPL-2.0
license-file:        LICENSE
author:              Serokell
maintainer:          Serokell <hi@serokell.io>
copyright:           2022 Serokell <https://serokell.io>

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/serokell/tzbot#readme>

library:
  source-dirs: src
  dependencies:
  - universum
  - aeson
  - aeson-casing
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - cache
  - case-insensitive
  - clock
  - containers
  - directory
  - fmt
  - deriving-aeson
  - dlist
  - fmt
  - formatting
  - guid
  - glider-nlp
  - http-client
  - http-client-tls
  - http-types
  - katip
  - lens
  - lens-aeson
  - managed
  - megaparsec
  - nyan-interpolation
  - o-clock
  - random
  - optparse-applicative
  - servant-auth
  - servant-auth-client
  - servant-client
  - servant-client-core
  - servant-server
  - slacker
  - string-conversions
  - template-haskell
  - text
  - text-metrics
  - time
  - time-compat
  - transformers
  - tz
  - tztime
  - unliftio
  - unordered-containers
  - utf8-string
  - validation
  - vector
  - yaml
  - utf8-string

executables:
  tzbot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - universum
    - tzbot

tests:
  tzbot-test:
    main:                Main.hs
    source-dirs:         test
    build-tools:      tasty-discover:tasty-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - universum
    - tzbot
    - aeson
    - containers
    - hspec
    - http-types
    - katip
    - nyan-interpolation
    - servant-client-core
    - string-conversions
    - tasty
    - tasty-hspec
    - tasty-hunit
    - tasty-quickcheck
    - text
    - time
    - tztime
    - QuickCheck
  doctests:
    main:                doctests.hs
    source-dirs:         test
    other-modules:       []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - universum
    - doctest-parallel

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-name-shadowing
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-safe-haskell-mode
  - -Wno-prepositive-qualified-module
  - -Wno-monomorphism-restriction
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wunused-packages

default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NegativeLiterals
  - NoImplicitPrelude
  - NumDecimals
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - ScopedTypeVariables
  - StandaloneDeriving
  - StrictData
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  - ViewPatterns
