# SPDX-FileCopyrightText: 2022 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

steps:
  - label: check trailing whitespaces
    command: nix build -L .#checks.x86_64-linux.trailing-whitespace

  - label: shellcheck
    command: nix build -L .#checks.x86_64-linux.shellcheck

  - label: validate cabal files
    command: nix develop .#ci -c ./scripts/validate-cabal-files.sh

  - label: stylish
    command: nix build -L .#checks.x86_64-linux.stylish-haskell
    soft_fail:
      - exit_status: 1

  - label: lint
    command: nix build -L .#checks.x86_64-linux.hlint

  - label: build
    key: build
    command: nix build -L .#checks.x86_64-linux.build-all

  - label: tests
    depends_on: build
    commands:
      - nix build -L .#checks.x86_64-linux.test
      - nix develop .#doctest -c runghc test/doctests.hs

  - label: xrefcheck
    command: nix run github:serokell/xrefcheck
    soft_fail:
      - exit_status: 1

  - label: REUSE lint
    command: nix build -L .#checks.x86_64-linux.reuse-lint

  # wait for all checks to finish
  - wait

  - label : deploy staging
    command: nix develop .#ci -c deploy .#staging --ssh-user deploy --skip-checks
    branches: staging
